/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package schoolsystem;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Our
 */
public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    public Admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        lblLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnDeleteLearner = new javax.swing.JButton();
        btnSearchLearner = new javax.swing.JButton();
        btnDeleteParent = new javax.swing.JButton();
        btnSearchParent = new javax.swing.JButton();
        btnDeleteTeacher = new javax.swing.JButton();
        btnSearchTeacher = new javax.swing.JButton();
        btnReturn = new javax.swing.JButton();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("frmAdmin"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        lblLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblLabel.setText("Admin Access");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Learner");

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable3);

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTable4);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Parent");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Teacher");

        btnDeleteLearner.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        btnDeleteLearner.setText("Delete Learner");
        btnDeleteLearner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteLearnerActionPerformed(evt);
            }
        });

        btnSearchLearner.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        btnSearchLearner.setText("Search Learner");
        btnSearchLearner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchLearnerActionPerformed(evt);
            }
        });

        btnDeleteParent.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        btnDeleteParent.setText("Delete Parent");
        btnDeleteParent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteParentActionPerformed(evt);
            }
        });

        btnSearchParent.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        btnSearchParent.setText("Search Parent");
        btnSearchParent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchParentActionPerformed(evt);
            }
        });

        btnDeleteTeacher.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        btnDeleteTeacher.setText("Delete Teacher");
        btnDeleteTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteTeacherActionPerformed(evt);
            }
        });

        btnSearchTeacher.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        btnSearchTeacher.setText("Search Teacher");
        btnSearchTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchTeacherActionPerformed(evt);
            }
        });

        btnReturn.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        btnReturn.setText("Home");
        btnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3)
                            .addComponent(jScrollPane4)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnDeleteParent)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSearchParent)
                                .addGap(185, 185, 185))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnDeleteTeacher)
                                .addGap(18, 18, 18)
                                .addComponent(btnSearchTeacher)
                                .addGap(182, 182, 182))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnReturn)
                                        .addGap(147, 147, 147)
                                        .addComponent(lblLabel))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 4, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDeleteLearner)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSearchLearner)
                        .addGap(195, 195, 195))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLabel)
                    .addComponent(btnReturn))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnDeleteLearner)
                    .addComponent(btnSearchLearner))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(btnDeleteParent)
                    .addComponent(btnSearchParent))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(btnDeleteTeacher)
                    .addComponent(btnSearchTeacher))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteLearnerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteLearnerActionPerformed
        try {
            Class.forName("com.mysql.jdbc.Driver");
             Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/student_db", "zaynab", "09031992");
             System.out.println("Database Connection Success");

            Statement st = con.createStatement();
            String Deleted = JOptionPane.showInputDialog("Enter Contact number of record to be deleted :");
            String q = "SELECT * FROM tblLearners WHERE parent_contact ='" + Deleted + "'";
            ResultSet rs = st.executeQuery(q);
            String answer = JOptionPane.showInputDialog("Are you sure you want to Delete this record YES/NO");
            if (answer.equalsIgnoreCase("Yes")) {
                q = "DELETE FROM tblLearners WHERE parent_contact='" + Deleted + "'";
                st.executeUpdate(q);
                System.out.println("Record Deleted...");
            } else {
                System.out.println("Record Not Found...");
            }
            con.close();
        } catch (Exception e) {
            System.out.println(e);
        }// TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteLearnerActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        Connection2DB c = new Connection2DB();
        c.ShowLeaner(jTable1);
        c.ShowParent(jTable4);
        c.ShowTeacher(jTable3);// TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void btnDeleteParentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteParentActionPerformed
        try {
             Class.forName("com.mysql.jdbc.Driver");
             Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/student_db", "zaynab", "09031992");
             System.out.println("Database Connection Success");

            Statement st = con.createStatement();
            String Deleted = JOptionPane.showInputDialog("Enter Contact number of record to be deleted :");
            String q = "SELECT * FROM tblParents WHERE parent_contact ='" + Deleted + "'";
            ResultSet rs = st.executeQuery(q);
            String answer = JOptionPane.showInputDialog("Are you sure you want to Delete this record YES/NO");
            if (answer.equalsIgnoreCase("Yes")) {
                q = "DELETE FROM tblParents WHERE parent_contact='" + Deleted + "'";
                st.executeUpdate(q);
                System.out.println("Record Deleted...");
            } else {
                System.out.println("Record Not Found...");
            }
            con.close();
        } catch (Exception e) {
            System.out.println(e);
        }// TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteParentActionPerformed

    private void btnDeleteTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteTeacherActionPerformed
     try {
             Class.forName("com.mysql.jdbc.Driver");
             Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/student_db", "zaynab", "09031992");
             System.out.println("Database Connection Success");

            Statement st = con.createStatement();
            String Deleted = JOptionPane.showInputDialog("Enter Contact number of record to be deleted :");
            String q = "SELECT * FROM tblTeachers WHERE teacher_contact ='" + Deleted + "'";
            ResultSet rs = st.executeQuery(q);
            String answer = JOptionPane.showInputDialog("Are you sure you want to Delete this record YES/NO");
            if (answer.equalsIgnoreCase("Yes")) {
                q = "DELETE FROM tblTeacher WHERE teacher_contact ='" + Deleted + "'";
                st.executeUpdate(q);
                System.out.println("Record Deleted...");
            } else {
                System.out.println("Record Not Found...");
            }
            con.close();
        } catch (Exception e) {
            System.out.println(e);
        }   // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteTeacherActionPerformed

    private void btnSearchLearnerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchLearnerActionPerformed
      try {
			 Class.forName("com.mysql.jdbc.Driver");
             Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/student_db", "zaynab", "09031992");
             System.out.println("Database Connection Success");

				Statement st = con.createStatement();
		   String Content = JOptionPane.showInputDialog("Enter learner name to search :");
		   String q="SELECT * FROM tblStudents WHERE student_name LIKE'%"+Content+"%'";
		   ResultSet rs= st.executeQuery(q);
		con.close();
		   }catch(Exception e){
				System.out.println(e);
			}
		// TODO add your handling code here:
    }//GEN-LAST:event_btnSearchLearnerActionPerformed

    private void btnSearchParentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchParentActionPerformed
   try {
            Class.forName("com.mysql.jdbc.Driver");
             Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/student_db", "zaynab", "09031992");
             System.out.println("Database Connection Success");

				Statement st = con.createStatement();
		   String Content = JOptionPane.showInputDialog("Enter parent name to search :");
		   String q="SELECT * FROM tblParents WHERE parent_name LIKE'%"+Content+"%'";
		   ResultSet rs= st.executeQuery(q);
		con.close();
		   }catch(Exception e){
				System.out.println(e);
			}        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchParentActionPerformed

    private void btnSearchTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchTeacherActionPerformed
        try {
			 Class.forName("com.mysql.jdbc.Driver");
             Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/student_db", "zaynab", "09031992");
             System.out.println("Database Connection Success");

				Statement st = con.createStatement();
		   String Content = JOptionPane.showInputDialog("Enter teacher name to search :");
		   String q="SELECT * FROM tblTeachers WHERE teacher_name LIKE'%"+Content+"%'";
		   ResultSet rs= st.executeQuery(q);
		con.close();
		   }catch(Exception e){
				System.out.println(e);
			}  // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchTeacherActionPerformed

    private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnActionPerformed
      HomePage frmHome = new HomePage();
      frmHome.setVisible(true);
      this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_btnReturnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeleteLearner;
    private javax.swing.JButton btnDeleteParent;
    private javax.swing.JButton btnDeleteTeacher;
    private javax.swing.JButton btnReturn;
    private javax.swing.JButton btnSearchLearner;
    private javax.swing.JButton btnSearchParent;
    private javax.swing.JButton btnSearchTeacher;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JLabel lblLabel;
    // End of variables declaration//GEN-END:variables
}
